module.exports = {
  purge: [],
  theme: {
    extend: {
      colors: {
        brown: '#996633',
        lightBrown: '#f8f2ec',
        darkBrown: '#392714',
      },
    },
  },
  variants: {
    backgroundColor: [
      'responsive',
      'group-hover',
      'group-focus',
      'focus-within',
      'first',
      'last',
      'odd',
      'even',
      'hover',
      'focus',
      'active',
      'visited',
      'disabled',
    ],
    textColor: [
      'responsive',
      'group-hover',
      'group-focus',
      'focus-within',
      'first',
      'last',
      'odd',
      'even',
      'hover',
      'focus',
      'active',
      'visited',
      'disabled',
    ],
  },
  plugins: [],
};
